# Database Configuration
database:
  enabled: true
  type: "MySQL"  # Currently only MySQL is supported
  host: "localhost"
  port: 3306
  database: "essentials"
  username: "root"
  password: "password"
  # Connection pool settings
  pool:
    minimum-idle: 2
    maximum-pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# General Settings
settings:
  # Enable UUID support (required for 1.7.10+)
  uuid-support: true

  # Save data when player leaves the server
  save-on-quit: true

  # Load data when player joins the server
  load-on-join: true

  # Delete local userdata file after saving to database
  delete-local-after-save: true

  # Delete entire userdata folder on server shutdown/restart
  delete-userdata-folder-on-shutdown: false

  # Save player data to database in async to prevent lag
  async-operations: true

  # Sync interval in minutes (0 = disabled)
  auto-sync-interval: 0

# Data Management
data:
  # Filter what data to save/load (set to false to exclude)
  filters:
    enabled: false  # Disable filtering to save ALL data completely
    homes: true
    money: true
    mail: true
    kits: true
    cooldowns: true
    warps: true
    jail: true
    mutes: true
    social-spy: true
    god-mode: true
    fly: true
    nicknames: true
    ignore-list: true
    teleport-requests: true

  # Compress data before storing in database
  compress-data: true

  # Maximum data size per player in KB (0 = unlimited for complete data preservation)
  max-data-size: 0

# Cleanup Settings
cleanup:
  # Remove inactive users from database
  enabled: false

  # Days of inactivity before removal
  inactive-days: 365

  # Run cleanup on server start
  cleanup-on-start: false

  # Cleanup interval in hours (0 = disabled)
  cleanup-interval: 24

# Shop Plugin Integration
shop-integration:
  # ChestShop support
  chestshop:
    enabled: false
    offline-sales: true
    offline-buy-orders: true

  # AuctionHouse support
  auctionhouse:
    enabled: false
    offline-auctions: true

  # PlayerShopGUI+ support
  playershopgui:
    enabled: false
    offline-sales: true

  # ShopChest support
  shopchest:
    enabled: false
    offline-sales: true
    offline-buy-orders: true

# Command Settings
commands:
  # Enable balance top command from database
  balance-top:
    enabled: true
    cache-duration: 300  # seconds

  # Import/Export commands
  import-export:
    enabled: true
    backup-before-import: true
    backup-before-export: true

# Debug and Logging
debug:
  enabled: false
  log-database-operations: false
  log-file-operations: false
  performance-monitoring: false

# Messages
messages:
  prefix: "&7[&bEssentialsSQL&7]&r "
  data-loading: "&aLoading your data..."
  data-saving: "&aSaving your data..."
  data-load-failed: "&cFailed to load your data!"
  data-save-failed: "&cFailed to save your data!"
  import-success: "&aSuccessfully imported {count} players!"
  export-success: "&aSuccessfully exported {count} players!"
  cleanup-success: "&aCleanup completed! Removed {count} inactive players."
  no-permission: "&cYou don't have permission to use this command!"